# Generated by Django 3.1 on 2020-11-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20201027_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kind'),
        ),
    ]
